// src/components/Construction.tsx
import {Card, Col, Container, CardBody, CardHeader} from "@paljs/ui";


const Construction = () => (
    <Container>
        <Col>
            <Card>
                <img src="/pictures/undraw_building_websites_i78t.svg" alt="Construction site"/>
                <CardHeader>yikes!</CardHeader>
                <CardBody>Still working on that one.</CardBody>
            </Card>
        </Col>
    </Container>
);

export default Construction;

// components/Construction.vue
<template>
  <v-container>
    <v-col>
      <v-card>
        <v-img src="/pictures/undraw_building_websites_i78t.svg"></v-img>
        <v-card-title>yikes!</v-card-title>
        <v-card-text>Still working on that one.</v-card-text>
      </v-card>
    </v-col>
  </v-container>
</template>

<script>
export default {
  name: 'Construction',
}
</script>

<style scoped></style>
